project:
  type: book


book:
  title: "JRaviLab docs"
  subtitle: "For members of the JRaviLab: past, present, and future!"
  author:
  - name: "Janani Ravi & members of JRaviLab"
    email: janani.ravi@cuanschutz.edu
  reader-mode: true
  date: "last-modified"

  repo-url: https://github.com/jravilab/lab_docs
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - onboarding.qmd
    - culture.qmd
    - howto.qmd
    - resources.qmd
    - offboarding.qmd
  appendices:
    - meetings.qmd
    - howto_code_review.qmd
    - howto_write_sourcecode.qmd
    - howto_work_remotely.qmd
    - howto_make_poster.qmd
    - howto_write_paper.qmd
    - career-dev.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
      # light: flatly
      # dark: darkly
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

