project:
  type: book
  #type: website
  output-dir: docs

book:
  title: "JRaviLab docs"
  subtitle: "For members of the JRaviLab: past, present, and future!"
  author: "Janani Ravi"
  #date: `r date()`
  chapters:
    - index.qmd
    - onboarding.qmd
    - howto.qmd
    - resources.qmd
    - meetings.qmd
    - offboarding.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

