# Make a poster

## Questions to address

In the poster, clearly and concisely explain what you have done in terms of the 4 questions:

1\. What is the problem? why is it important/significant? \| Background/Overview

2\. What are the current approaches to address this problem & what are their limitations? *aka* Gaps in knowledge \| Background/Overview

3\. What is your approach, what are the results, and what are the take-homes? \| Workflow, Results sections, Summary/Conclusions (\>60% of your poster)

4\. What are the next steps and, in general, who cares? tying it back to the big picture \| Future Directions/Significance

## Main elements of the poster

1.  Title, authors, affiliations, group, university logo
2.  Background/Overview (w/ fig)
3.  Approach/Methods w/ your flowchart/cartoon workflow \| methods/tools can be spelled out for each logical step of the pipeline
4.  Results, Results, Results \| in various shapes and forms, but mostly said with clear readable figures, screenshots, tables (if plots can't be made)
5.  Summary/Conclusions & Future Directions \| separately or together based on how much you have to say for each
6.  Acknowledgments & References (could be together/separate)
7.  Contact info -- group's, yours, ... how/whom to reach if they have questions.

### Other Tips

-   Font sizes readable at 100% zoom from a 2-3ft distance
-   Clear BIG section headings
-   Use colors, but 'wisely!'
-   Figures \> flowcharts \> bullet points \>\>\> blocks of text (avoid)
-   Where to make? Google Slides (when collaborative + preferred), Keynote/PowerPoint

## References

-   [How to Create a Research Poster: Poster Basics \| NYU Libraries](https://guides.nyu.edu/posters)
-   [Ten Simple Rules for a Good Poster Presentation \| PLoS CompBio](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0030102)
-   [Simple Rules to Make an Effective Scientific Presentation \| my slides](https://jravilab.github.io/talk/2019-cvm/)
-   [Poster/Lightning Talk Guidelines from Women+ Data Science Symposium](https://women-plus-datascience.github.io/home/poster-talk-guidelines)
-   [A guide to poster making for scientific conferences \| Sina Rueger](https://sinarueeger.github.io/post/scientific-poster/)
-   [Tips for presenting a scientific poster at a conference \| Scientifica Neurowire](https://www.scientifica.uk.com/neurowire/tips-for-presenting-your-scientific-poster-at-a-conference)
-   [How to make an effective poster \| UC Davis undergraduate research center](https://urc.ucdavis.edu/sites/g/files/dgvnsk3561/files/local_resources/documents/pdf_documents/How_To_Make_an_Effective_Poster2.pdf)

### Example posters

*To be added.*
