# Meetings

Please update this semester's meeting schedule [here](https://docs.google.com/spreadsheets/d/14919WwHIiKFFBcYZgF9wxACIYqh-gW-2QeDyM4WU28E/edit#gid=0).

## Format

### Weekly lab meetings 
-   These provide a space for everyone to share updates and roadblocks, and depending on the needs of the group, these meetings can be in a roundtable format where everybody who has updates can share them briefly (<10min per person), longer form updates or presentations for 1-2 people (<30min per person), or the entire slot can be reserved so one person can give a practice talk or major project summaries (<60min per person). We operate a Google Calendar where members can put themselves down for specific topics, times, and dates. In all cases, these weekly lab meetings are required for all members to attend.

### Weekly project-specific meetings
-   These give lab members under a broadly shared project/topic umbrella a space for more detailed discussions and to seek specific feedback and help from their peers in the same or similar topics. These meetings are only required for those in the relevant associated projects, but are open to any members curious to sit in, learn, and  contribute. Like the weekly lab meetings, lab members can schedule themselves for specific topics or times. Because of their more focused scope, there may be times where these meetings can be quick updates dropped in Slack instead, and all involved lab members should communicate regularly to ensure each meeting is necessary.

### One-on-one meetings or small group meetings 
-   These more direct meetings can be set up as-needed. To easily schedule a one-on-one with Janani, [please use this booking link](bit.ly/janani-cucal).

### Journal clubs
-   Journal club serves as opportunities to present interesting new research papers from other groups. For journal clubs, all members of the lab must read the selected paper ahead of time and be prepared to help their peers explain it. Likewise, to be respectful of the time commitments of others, the presenter must share their selected paper at least a few days before the meeting, and preferably the week before to give everyone a chance to read it thoroughly. 

-   The format of journal club is largely up to the presenter, but it should walk briefly through the background to the problem, the question or need the paper addresses, how they did the work, what the results were, and how it ties back to the larger problems in the field and future directions. While the presenter can take the lead and walk the group through everything, journal clubs are a lot more engaging and educational with participation, so having the audience explain figures and interpretations is an easy way to ensure people are learning instead of just listening.

### Primers
-   Technical primers can be great practice on teaching a topic by sharing how-to or tutorial lectures on subjects of your choosing. These are great opportunities to share a skill or approach with the group so we can all benefit from it. 

-   Additionally, these are spaces where we can invite an outside presenter to share with us (for example, the [Department of Biomedical Informatics' Software Engineering Team](https://cu-dbmi.github.io/set-website/about), or the [CU Office of Diversity, Equity, Inclusion & Community Engagement](https://www.cuanschutz.edu/offices/diversity-equity-inclusion-community), or a scientist with subject expertise from another lab group). It is up to the group collectively to decide which primer topics are appropriate.

### Co-work sessions
-   Organized as desired, and can be in-person or virtual. Have a paper or a grant deadline? Need to do some code review? Looking to catch up on recent literature? A co-work session is a great place to get these done in a focused but still social setting. These typically work best if you bring a task or to-do list, but are also good to set up regularly if you're working remotely for any extended periods of time to keep in touch and allow more natural interactions with your colleagues.  

### Weekly software engg meetings
-   Meetings with the [DBMI SET](https://cu-dbmi.github.io/set-website/about) on software and UI/UX design and implementation, as well as work on our JRaviLab server, software applications like [MolEvolvR](https://jravilab.cuanschutz.edu/molevolvr/), or work on the [CU Alpine HPC cluster](https://www.colorado.edu/rc/alpine).

### (Bi)weekly/monthly collab meetings
-   Less frequent except during sprints, these are meetings with our collaborators on joint projects. They may involve sharing goals, blockers, and milestones, or might involve a collaborator working as a consultant to give advice or feedback from an outside perspective on a project.    

## Logistics

-   GitHub issues/project for detailed project to-do's
-   Shared Outlook Calendar for meetings, deadlines, RLEL & other events!
-   Semester planning meeting (once per sem, during the first month)
-   Slack for everything else! ðŸ˜ƒ

## Schedule and times 
Always confirm the exact meeting schedule with our shared Outlook Calendar and [Sheets document](https://docs.google.com/spreadsheets/d/14919WwHIiKFFBcYZgF9wxACIYqh-gW-2QeDyM4WU28E/edit#gid=0), but below are the usual meeting times.

### Monthly/Weekly individual check-ins:

Book via [Outlook bookings](https://bit.ly/janani-cucal).

### Group meetings (~15min per person)
-   Weekly group meeting (All members) \| Fri 10.30a MST (wk)
-   Journal clubs/[Bioinfo primer series](https://github.com/JRaviLab/bioinfo-primers) \| Thu 11a MST (wk)
-   Software engg (MolEvolvR, server, & such) \| Mon 1p MST (wk) \| DBMI-SET (CU)
-   Microbial G2P (MolEvolvR/CompGenomeR/AMR) \| Mon 2.30p MST (wk)
-   Host response and disease/drug signatures \| Thu, 9a MST (wk) \| w/ KrishnanLab (CU)
-   AMR ms \| TBD (wk)
-   EEPID \| TBD (wk) \| w/ WaleLab (MSU)

### DBMI seminar schedule
Posted by the [DBMI seminar committee](https://github.com/jananiravi/dbmi_seminar)

### Monthly Group Socials â˜• ðŸµ ðŸ¥

<TBD>

-   Random discussions/catch-up
-   Online games: https://jackbox.tv \| https://drawbattle.io
-   Coffee/tea or ice cream for local folks
-   Once in a while, we can dedicate the group socials to fun topics close to your heart (e.g., music, sports, books, food, ...)!
